server {
    # Hacemos que Nginx escuche en el puerto que se expone en el Dockerfile
    listen 8081;
    server_name localhost;

    location / {
        # indicamos a Nginx dónde se encuentran los archivos estáticos de React
        root /usr/share/nginx/html;
        index index.html index.htm;
        
        # Si el archivo solicitado no se encuentra, redirigimos a index.html 
        # para que React Router maneje la navegación en el lado del cliente      
        try_files $uri $uri/ /index.html;
    }
}