version: '3.8'

services:
  # --- BASE DE DATOS COMPARTIDA (Optimiza RAM en AWS) ---
  db-sistema:
    image: mysql:8.0
    container_name: db-sistema
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      # Inicializa con la base de despacho por defecto
      MYSQL_DATABASE: ${MYSQL_DB_DESPACHO}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_sistema_data:/var/lib/mysql
      # Script opcional si necesitas inicializar la segunda base de datos automáticamente
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - sistema-network
    restart: always

  # --- MICROSERVICIO: BACKEND DESPACHO ---
  api-despacho:
    image: tu_usuario_docker/api-despacho:latest # <- Reemplaza con tu usuario de DockerHub
    container_name: api-despacho
    ports:
      - "8082:8085" # EXTERNO 8082 (Tu puerto) -> INTERNO 8085 (Tu application.properties)
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DESPACHO_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DESPACHO_USER}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DESPACHO_PASS}
    depends_on:
      - db-sistema
    networks:
      - sistema-network
    restart: always

  # --- MICROSERVICIO: BACKEND VENTA ---
  api-venta:
    image: tu_usuario_docker/api-venta:latest # <- Reemplaza con tu usuario de DockerHub
    container_name: api-venta
    ports:
      - "8083:8084" # EXTERNO 8083 (Tu puerto) -> INTERNO 8084 (Tu application.properties)
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_VENTA_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_VENTA_USER}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_VENTA_PASS}
    depends_on:
      - db-sistema
    networks:
      - sistema-network
    restart: always

  # --- FRONTEND (REACT APP) ---
  frontend-app:
    image: tu_usuario_docker/frontend-app:latest # <- Reemplaza con tu usuario de DockerHub
    container_name: frontend-app
    ports:
      - "8081:8081" # 8081 : 8081 (Exigido por el Nginx sin root)
    environment:
      - REACT_APP_API_DESPACHO_URL=${REACT_APP_API_DESPACHO_URL}
      - REACT_APP_API_VENTA_URL=${REACT_APP_API_VENTA_URL}
    networks:
      - sistema-network
    restart: always

volumes:
  mysql_sistema_data: # Cumple con el criterio de persistencia de la rúbrica

networks:
  sistema-network:
    driver: bridge