spring.application.name=Springboot-API-REST

server.port=8085
server.address=0.0.0.0

# Configuración de base de datos
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver

# Configuración de Hibernate simplificada
spring.jpa.hibernate.ddl-auto=update
# Eliminamos la propiedad hibernate.dialect ya que Hibernate 6.6 la detecta automáticamente