apiVersion: v1
kind: Service
metadata:
  name: backend-ventas
  namespace: devopsVG
  labels:
    app: backend-ventas
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: backend-ventas
  ports:
    - name: http
      port: 8084
      targetPort: 8084

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-ventas-hpa
  namespace: devopsVG
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend-ventas
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
